import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15
decorations = "Buttonless"
opacity = 1.0
blur = true
startup_mode = "SimpleFullscreen"
# startup_mode = "Windowed"
option_as_alt = "Both"

# [window.position] # center window
# x = 640
# y = 300

[font]
normal = { family = "SFMono Nerd Font", style = "Light" }
size = 20

[cursor]
style = {shape="Block", blinking="Always"}

# [colors]
# cursor = {cursor = "#fe8019"}

[mouse]
hide_when_typing = true

[bell]
animation = "Linear"
